name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate short SHA
        uses: benjlevesque/short-sha@v2.2
        id: short-sha

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:${{ steps.short-sha.outputs.sha }}
